### ISSUE TITLE
Validate user details form

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Income-Tax-Calcultor#4] opened 2021-06-04 12:46 UTC
![image](https://user-images.githubusercontent.com/56196640/120802634-492ab500-c560-11eb-9dad-21d97228f165.png)

Form must not accept wrong inputs like :
Name = k56% 
Contact = 983@gmajdk83hf\
Email = jdhd8h#$%

A warning must appear when a user makes illegal inputs.

**Comment by deek121477** [comment] 2021-06-05 10:52
I would like to work on this issue. Could you please assign me?

**Comment by QAZIMAAZARSHAD** [comment] 2021-06-05 16:32
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by techabhi08** [comment] 2021-06-06 03:19
Hello @QAZIMAAZARSHAD I would like to contibute to this. Please assign me this issue.

**Comment by Prateek027-S** [comment] 2021-06-06 08:00
Hello, I want to solve this issue. Please assign me the task.

**Comment by QAZIMAAZARSHAD** [comment] 2021-06-06 16:50
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Since this is a bug, I'll merge only the first PR which will completely resolve this issue.

**Comment by hellosafwaan** [comment] 2021-06-09 16:22
I would like to solve this, please asign the issue to me.

**Comment by QAZIMAAZARSHAD** [comment] 2021-06-09 16:28
Remember, Since this is a bug, I'll merge only the first PR which will completely resolve this issue.

**Comment by Prateek027-S** [comment] 2021-06-10 02:54
Hey, @QAZIMAAZARSHAD  I wanted to ask if I can also add a button called 'Validate' which will validate each input in the Entry widget and show the warning if any of the input value fails to pass the Validation. Because if not, then it would try to Validate the input while the user is typing the entry giving unnecessary warnings.

**Comment by QAZIMAAZARSHAD** [comment] 2021-06-10 07:10
Fine @hellosafwaan.
Wait till I review your PR.

**Comment by QAZIMAAZARSHAD** [comment] 2021-06-10 07:11
> Hey, @QAZIMAAZARSHAD I wanted to ask if I can also add a button called 'Validate' which will validate each input in the Entry widget and show the warning if any of the input value fails to pass the Validation. Because if not, then it would try to Validate the input while the user is typing the entry giving unnecessary warnings.

No need for a button @Prateek027-S.
Also, since a PR has been made this issue will likely get closed.

**Comment by Lovishk022** [comment] 2021-06-11 08:43
Hey! @QAZIMAAZARSHAD Please assign me this issue under LGM-SOC. I resolved it and just want you to see that.

**Comment by QAZIMAAZARSHAD** [comment] 2021-06-11 08:53
@Lovishk022 this issue is already assigned to others and has already been resolved.

**Comment by ghost** [comment] 2021-06-11 19:22
@QAZIMAAZARSHAD If the issue is resolved properly, then please close the issue or add some more points to note.

**Comment by QAZIMAAZARSHAD** [comment] 2021-06-12 05:00
> @QAZIMAAZARSHAD If the issue is resolved properly, then please close the issue or add some more points to note.

Not closed yet, but will be closed soon.
Assignees have already made the PR.

**Comment by QAZIMAAZARSHAD** [comment] 2021-06-12 05:01
> Hey! @QAZIMAAZARSHAD Please assign me this issue under LGM-SOC. I resolved it and just want you to see that.

This issue is assigned to others and will be closed soon.
Look for any other issues.

**Comment by QAZIMAAZARSHAD** [comment] 2021-06-12 05:11
@hellosafwaan and @Prateek027-S both of you, your changes are wrong.

Application crashes after your changes.

Look into this.
I have closed your PR, update your repo with main then make the changes.

**Comment by QAZIMAAZARSHAD** [comment] 2021-06-12 05:14
@Prateek027-S, your PR was merged by mistake I have reverted the changes.

This issue is still open.

**Comment by Lovishk022** [comment] 2021-06-12 05:21
@QAZIMAAZARSHAD Please assign to me if it is still open

**Closed as completed** 2021-06-12 08:23 UTC
Labels: bug, LGMSOC21, 🟥 Level4
